const NUM_FIXTURE_CLASSES = 9;
const LOOP_DURATION = 32; // 2bars x 16th note

const MIN_ONSETS_THRESHOLD = 5; // ignore loops with onsets less than this num

const ORIGINAL_DIM = NUM_FIXTURE_CLASSES * LOOP_DURATION;


exports.NUM_FIXTURE_CLASSES = NUM_FIXTURE_CLASSES;
exports.LOOP_DURATION = LOOP_DURATION;
exports.ORIGINAL_DIM = ORIGINAL_DIM;
exports.MIN_ONSETS_THRESHOLD = MIN_ONSETS_THRESHOLD;
